# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370a6d9ddbe13a039c6ac123b3cac6dd8f80b4d03cd19fd214c0e1de838129868e16d2f23619624787819b217992f7e48c8f1cd0cee7470d0602b7d476abe290

test:
  secret_key_base: 357f5e62b2cda50b603b3c262891a1867014db9dcf26d6ab62a51c7b2c3943302a43ff0362167b5729fe058a7c04a4dbf6945cae1e045d4a6c43e54e8b1f3590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
